{% set name = "scikit-optimize" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b5602b22c7aacabe3afd36619f662d1f287f2e3fe9a5aa19bbc83f851b30b7bf
  patches:
    - 0001-replace-deprecated-np.int.patch
    - 0002-use-compatible-mse-criteria-with-scikit-learn.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - patch  # [not win]
    - m2-patch  # [win] 
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.19.1
    - scikit-learn >=0.20.0
    - matplotlib-base >=2.0.0
    - pyaml >=16.9
    - joblib >=0.11

# Skip tests: this package does not seem being actively maintained
# See the many issues that also affects tests, and comments
# that mention that the package is not maintained e.g.:
#   https://github.com/scikit-optimize/scikit-optimize/issues/1137
#   https://github.com/scikit-optimize/scikit-optimize/issues/1137
#
# All that fail in test_common.py
# {% set tests_to_skip = "test_per_second_api" %}
# {% set tests_to_skip = tests_to_skip + " or test_early_stopping_delta_x" %}
# {% set tests_to_skip = tests_to_skip + " or test_consistent_x_iter_dimensions" %}
# {% set tests_to_skip = tests_to_skip + " or test_repeated_x" %}
# {% set tests_to_skip = tests_to_skip + " or test_mixed_spaces" %}
# {% set tests_to_skip = tests_to_skip + " or test_categorical_init_vals" %}
# {% set tests_to_skip = tests_to_skip + " or test_init_vals" %}
# {% set tests_to_skip = tests_to_skip + " or test_init_points_and_models" %}
# {% set tests_to_skip = tests_to_skip + " or test_init_vals_and_models" %}
# {% set tests_to_skip = tests_to_skip + " or test_minimizer_with_space" %}
# {% set tests_to_skip = tests_to_skip + " or test_fixed_random_states" %}
# {% set tests_to_skip = tests_to_skip + " or test_minimizer_api" %}
# # All that fail in py<311 in other test modules
# {% set tests_to_skip = tests_to_skip + " or test_reproducible_runs" %}        # [py<311]  
# {% set tests_to_skip = tests_to_skip + " or test_same_set_of_points_ask" %}   # [py<311]
# {% set tests_to_skip = tests_to_skip + " or test_all_points_different" %}     # [py<311]
# {% set tests_to_skip = tests_to_skip + " or test_constant_liar_runs" %}       # [py<311]
# {% set tests_to_skip = tests_to_skip + " or test_optimizer_base_estimator_string_smoke" %}  # [py<311]
# {% set tests_to_skip = tests_to_skip + " or test_exhaust_initial_calls" %}    # [py<311]
# {% set tests_to_skip = tests_to_skip + " or test_optimizer_copy" %}           # [py<311]
# {% set tests_to_skip = tests_to_skip + " or test_acq_optimizer_with_time_api" %}  # [py<311]
# {% set tests_to_skip = tests_to_skip + " or test_returns_result_object" %}    # [py<311]
# {% set tests_to_skip = tests_to_skip + " or test_model_queue_size" %}         # [py<311]
# {% set tests_to_skip = tests_to_skip + " or test_multiple_asks" %}            # [py<311]
# {% set tests_to_skip = tests_to_skip + " or test_tree_based_minimize" %}      # [py<311]
# {% set tests_to_skip = tests_to_skip + " or test_categorical_integer" %}      # [py<311]
# {% set tests_to_skip = tests_to_skip + " or test_dump_and_load_optimizer" %}  # [py<311]
# {% set tests_to_skip = tests_to_skip + " or test_deadline_stopper" %}  # [win]
# {% set tests_to_skip = tests_to_skip + " or test_timer_callback" %}    # [win]
# {% set tests_to_skip = tests_to_skip + " or test_real" %}              # [linux-64]


test:
  imports:
    - skopt
    - skopt.learning
    - skopt.learning.gaussian_process
    - skopt.optimizer
    - skopt.space
  requires:
    - pip
    - pytest
  source_files:
    - skopt/tests
  commands:
    - pip check
    - export SKOPT_SKIP_NETWORK_TESTS=1  # [not win]
    - set SKOPT_SKIP_NETWORK_TESTS=1     # [win]
    # - pytest --showlocals --pyargs -m "not fast_test" -m "not slow_test" -m "not slow" --ignore=skopt/tests/test_benchmarks.py -k "not({{ tests_to_skip }})" skopt/tests
    - pytest --showlocals --pyargs -m "not fast_test" -m "not slow_test" -m "not slow" skopt/tests

about:
  home: https://scikit-optimize.github.io/
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Sequential model-based optimization toolbox.
  description: |
    Scikit-Optimize, or skopt, is a simple and efficient library to minimize (very) expensive and noisy black-box
    functions. It implements several methods for sequential model-based optimization. skopt aims to be accessible and
    easy to use in many contexts.
    The library is built on top of NumPy, SciPy and Scikit-Learn.
  dev_url: https://github.com/scikit-optimize/scikit-optimize
  doc_url: https://scikit-optimize.github.io/

extra:
  recipe-maintainers:
    - ukaratay
    - holgern
