{% set name = "scikit-optimize" %}
{% set version = "0.5.1" %}
{% set sha256 = "83e4bd90cd4cad8cc45fb2d5bc9bee5db7a6c5f58f85adf7d547a06e604c8006" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy >=0.14.0
    - scikit-learn >=0.19.1
    - matplotlib

test:
  imports:
    - skopt
    - skopt.learning
    - skopt.learning.gaussian_process
    - skopt.optimizer
    - skopt.space

about:
  home: https://scikit-optimize.github.io/
  license_file: LICENSE.md
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Sequential model-based optimization toolbox.'
  dev_url: https://github.com/scikit-optimize/scikit-optimize
  doc_url: https://scikit-optimize.github.io/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ukaratay
