# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ui4DrwXmOF3AvwjauVaFk7s4xV3GpJo4dCJFZ0VgAZTvDX7L4vzNjNE817MJAYHQfw90gc+tJZwipOF4Lf7LoHL3iDjeLWDVtnqZCzrqRiApueYL73KVqltwZELNz4bNrp/lsdiK+/mYrb1Sl4TEjy33bo0r5IX0DLYDVy0JnExAFs0rRv/Ta1PK1yptdpo5Eefa/2FxaXGPmmBFPQfh+vdj0Spjn+Bhj+ckcGbArDoVHbGO1Eub85c6nfy7I8eS0KvjM3WWuC/SE7SGqz7qer5w0FYCsA2gxB+5d/S26OZ1Rh8y3xsxx2rTTMh7YE45FPQdZ+1/k0Dg6w6R7KbaXiYg3BzOlkEUBsat2Ttx/9bL1qB+f5wP08g4wZW/5TDqF9E8W0BCSZUQg33tNz0kEQDuw8i4jveoA2F0HM+H5B/kJ8cNcHfL33M35HEYQ7FSGBJDqkvhYNfSrfetKgVH1u5cvVu7IFUuKxR1nXN+6mjw3+ySKXwMFd6pCMYGzWDVtBGBaX7CG+wqZBsmtKku3QIItM1d6sd98q9kqxx17pLM43/TblRCx2wMgKfrlEjGECXFMpFUsEaVjq226TCldimwfwfrJ8+ixv1zs27tQ4OmdTM9ANsFYKfD5y69491iOW6NxCfng29g586ZgISpLKD2Q/Gfg4uiYrMiydJgzVU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
