travis:
  secure:
    BINSTAR_TOKEN: Kj0qQVxL6Y6xVb4ZP/oJ3XPDszhDOppiDL9qjuhsSo16oiSL4UDOnFLnZ6BIFtlsBogrVLW/PiUhjbYy9vaEEYq7t6wPRRkZz0phvmqdUT8NT5Zlblq33eSpukmCFPx3p1sVeQczy21LubJw9NzmOOZztzUs3lqznzZOQCK+/+bYcc562MzBjLDbVKloNkYKRef2RIVCkh5Mj5JTZnngBhZsth7gMzoFT9ixNlfdKOtI6HWpskw+geM3iE+FqpekfzJ3Rg0fXyaYAboYo6KkDfFxm+0bScfZiB/LWiVaWV8R1FJWIdoMkK+1g/jqyITsboC3Yul11lmqBWIidyDVdztd4avOC+w8GzVrAAT8KKjHufM9Fky35QsiGDq9QxMQItlBNalMTqKhJgqI7m7gvuWnfT+ueGpJ6X5QBSHV18YtGuwB74iClxN7AtqKMzJoCm6xLhzBzo+QN1iKAgMCprJq7QEN/MKuEu0fenn0H42xY5m6LN1OcqUC1/RmZ4ALWq8SfVaIWL0bDjTtjTzaFNjQVHhqdv3+IPg+bEpciDqRqpmh0lJbSTQdSHLgNZU+36RD959n/ubmZh1WlcqctmQLhjF42ecKEhtw1BlT2vEbyGVpLWn6vkMlzYQxrUuDgED9ce6iswBlsgP/5HXj6gIeD31SAj+iKI1DBOqPQpY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
