travis:
  secure:
    BINSTAR_TOKEN: ui4DrwXmOF3AvwjauVaFk7s4xV3GpJo4dCJFZ0VgAZTvDX7L4vzNjNE817MJAYHQfw90gc+tJZwipOF4Lf7LoHL3iDjeLWDVtnqZCzrqRiApueYL73KVqltwZELNz4bNrp/lsdiK+/mYrb1Sl4TEjy33bo0r5IX0DLYDVy0JnExAFs0rRv/Ta1PK1yptdpo5Eefa/2FxaXGPmmBFPQfh+vdj0Spjn+Bhj+ckcGbArDoVHbGO1Eub85c6nfy7I8eS0KvjM3WWuC/SE7SGqz7qer5w0FYCsA2gxB+5d/S26OZ1Rh8y3xsxx2rTTMh7YE45FPQdZ+1/k0Dg6w6R7KbaXiYg3BzOlkEUBsat2Ttx/9bL1qB+f5wP08g4wZW/5TDqF9E8W0BCSZUQg33tNz0kEQDuw8i4jveoA2F0HM+H5B/kJ8cNcHfL33M35HEYQ7FSGBJDqkvhYNfSrfetKgVH1u5cvVu7IFUuKxR1nXN+6mjw3+ySKXwMFd6pCMYGzWDVtBGBaX7CG+wqZBsmtKku3QIItM1d6sd98q9kqxx17pLM43/TblRCx2wMgKfrlEjGECXFMpFUsEaVjq226TCldimwfwfrJ8+ixv1zs27tQ4OmdTM9ANsFYKfD5y69491iOW6NxCfng29g586ZgISpLKD2Q/Gfg4uiYrMiydJgzVU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
