travis:
  secure:
    BINSTAR_TOKEN: D3uqYybgegY3oKnpf8iwcWFJBuMccUXB7X6BMcqAuUfMFMDRkdl7C9NpH9xxKHC7P3U0td8xG4XqBWE61Kq7Wj4NIULSlShSP5I+MYOgbR0/LlUEpZlmidUf7o8HOfLPZam1FCRH1LVTuLk04Gy1YCoRQvvd32TTK7zA3SV9RRD2lPkw4+28c4KCp7vIWk8BTSXIH4+mWcxMzzduFmonYO8aD7sGoVo6o/FbCy8OEPfFiCK71aGai9zQuGVFyHE0FOKm/D6zpcfoOLFRzL2v/O6qTaMZ5047jF+7ozDqprZBZFrE02KTl7cckuHiMHxzjo53ZHd5M1ilTGfLfzZxB0/4OO8DN+WbjGHlv4/P94HUQVXXAAOiEwiZnX74KVYmWynjdeDb7735v6mJYA3pzjJGLAAgivBeJHz74qrfPgf7yG9ncLg7SpjQSU4E5pq7YeiAJG6bHFj8dfHtGZ3XWJrDvFAvX9KsaA0TDxrc7jRLrqOrVYbaED1bupzKsvMZ9SPkejCAg4SKaB2xtxHFXMckISUf0CXFKpggpRoFyl56uWSPnV7UzV2DCtV+X7VqkrqdNg9OOOapgXZCWvmExBk9RXJRTf2cW/myRyyunbiO+eo3u5mklwqdbm0U1wR4Gc8RHReN3bkX1qEnRf6ItRIeMjtJ57Wm+SqbmQhmdUE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
