travis:
  secure:
    BINSTAR_TOKEN: ekgpJMbQK6lWHwuxsiyu7G3AXOJO6hm4NSaqGJwoqks3vdrIiMlkTu5qTndVgHlhpNvSw0ODLWcDBky15nkE8JuL+oT5uFE7tRc0a1YURZ7SJ1yXyl/yVwOQAkC9xthV/CjyR+RwI5XWO6HzTl/FwGiwCM/1e/37Y6Qm8XpG+Ip85cHg1GB7QHtLhuV1jKf+jfqGrE574tWCptoiuUyDZY+gkCSagHPezsSY//iNn0V4OcUCHlQmKQNkFQJUfDA5phuMTDvax4y6f5+uuMTToxdEHUJ5+97zlvFzi+nBB2ZinNOMZmOD7tG3eYP0eI0qYsSlsmrYefgnOezOLxIWdFvrcmsRjJ7NRes+vA+elEVwVj+bHjjmuhLEqz47h2V2I6qOmfVMw9O/wK6clOCuefHkWsNzZDvIJzBoKE7wyyfJIr2wgVcZGyAPGh+0xxhGSy2DWILQ/Pdhp2T02xjq0NZpeGSaLisYIfTrALglhEpMjQu4BHjnla2PIzeSgsV3dLdeA3/FdTt4eEnT7SGBKUKvbTgOPEXgL3ARGJD/e+9dZWFTJuJBRS/qmUdQbIlBDE7jrnyCRqFY5xAnniIcVVvKpMUf9ofGnJTXYIUwf1ExziQU+7vtuIFvMgTVJOmDW9iHPe6GR5uhKA4vOtuimgY+8hVqY20v0ZSS4HiVIZg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
