travis:
  secure:
    BINSTAR_TOKEN: WzB9JhUR4px5q0JoAzlD6z8d9OG1+wEOynduNsuoa+u/avcimZhfx1r8eKTRC8mwhuxA+rYbRrd1c0eryrBFp7+c34P2IkYHsz8jwQrvwGr0GlDIgksyjPKC/MXeRTbpTKwNI+ALIBr550kHGfJp/bDUutFXWTWk4S1iBvEoyVxnZ21NEMPDPyix2gJuqIq/ScIjGhBk/y4QAWx/j9BhTIL0pzF7HsFK2iwhGG4thxJ8+FEkX60PlaUsqLp2HBrb9gmHaFGztL49uG324V/V+/czuii6/ZzTcH+2QTHVpOUMln7VpwGJlRxOFE4+aKIXCFQTzFbHBKHHncDb8RnbSxHXn4EYGFM8Qck+4GNHmrLLTQOIUnxmBfKZvQ5/ZoNOIaXXtGtPNFYLeAUKzSgT8ZX/7nlHjeG5eWmzS9z6xA23DHkzPRef6UroU30jxzA7gde8PF7MQfUdnO9C0R8IghV6JaJvqGzDYZFa3VMB8oxCg87EO/bf7o0Weo0OtoNuit1XDiIOLIquyZBnhzRjn40kF7NDR27xSNyPKFxfJR9GiyWestCwjziD6JtFf8j+2xcs2CLBDGToTMXILZKDZrEll72jXNOOkCoZTH9Mq1HaBZxOZBTDTsM2/PKyGWdKJ3+DB5wiVRGKVAHW+KiC2YssVIFLf52O/6TkA7jvjLI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
