travis:
  secure:
    BINSTAR_TOKEN: Ijvj0898ulBMh29W3dum9ooTlMtEjX1SDfeZNR3Omct6mKYYc17Nia+OV5WoSsNOl7ZwUbzU3NnSP+vOVF6CsGAIe1pZs14/pGKh6+4vJNt6D32HK7eXoGHdDImW4xwl994wRbx6HTaP/O8CcI+A0zgZ5Ew8Alkpoc3I/7s1g/Cd/2v5ePRhMWCgYFBIUdhB6zaLI8Fr9qNYUi50n9YoSd0coavD43xJnYNTxmKKo3mTLkK3vX2v2T5DtKY4OfFAIoLlS9A6EHXaNOrR9lMDNEvcEGA9miRhYeooVfD1iaiyLCGbNc2kjQOXzYhBZZR5/PNSWNZUJvBw1NJI74OS6GCj6Qm+uJxsd7G/gzVcz9kGD+IimVENwUFlX9UXoKcJj5BmArWohTpzvJkv6NpwlobXtsr3gK81A0kbTJHYmfAEaVnQszlDuggP9EVFwdSvyx3fQgLUZm1+4bEuAuR5M/V68u1l4PD2i1dwqlj3gg9Xq8DzUU34Bm5IyC7QSn2jhfI1DVan0GJd4HsYRcevFWiia/Z16fr7HTrWXu5hrPTL/TQYbfDx7beH+vnoIfC3d1wCFHnD3D1/LTXw7yZz4mfvL10ucTcweTQKJhwA1OUuXbH2J+OZAKliyUq8VAzLPvdvGmYOwLkI/Zuq9icJdfuZHrzT4rAY+pO5Yla6Q7A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
