travis:
  secure:
    BINSTAR_TOKEN: AEbv49Zd7zKOWs3IhhJOwJEA/F5PyxxkDQJYKDkUcxdVlqCrG1VHBPrbeQfnBtKkjB42XWTedX0i+70pt1jLxC9K7tzLgLwYtJ3mRB5AHnGgr9Y75f34nVCrE/r2mUtcWEMGQKa+matf+r5Lbq8lO9TU8XIxnvmfyDqxtXhKnLToETWNGb9B/i+r1+pePjMSoJ46P7hkabpAf05NTd0M5bsXFqaxkQEJ/exHptMNZHaC+yaLmGkX9gz0innvZhCuYV3ldDa+FkycDy9DE/HQuSy4JUIYsZT3Piu1VcBVXGkmp1hKCkEcTs5qeJgvsGAIoQNPcomQ3cr05W/jAChv3QqJWA/Tm1gwNXBl7RjnF/+RKzfKHqkOMeOsBcWb7TyO7g/t6AuQ3J7Ptz4pra6Msw6w6pZbxMMgq/twW9xITNBqYX7MKWb4mseElBCC7vUQ1Jnw71QHCSYueH8MNmvYzqmVdw2CExUxRUbQJ4+9vqk97TIv8UOnsATj5SRav3yxll/NLB7ORZEKUcPlf7QEh1qMs0QQceNFjhACSOfYwZE3ssvJyak+f3C4nroGLrMgMOecChIjtjl9qFtrIK+44dVuFOSN0z5k3CESks9dm+mD1ytLx38JV6bBewuZGGZFjyQ6qIjUQSom5TmYAMxg9nDrF6vYHNSFKH7ApyLizGQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
