travis:
  secure:
    BINSTAR_TOKEN: E6JuXTABg+2ZOoyo8M2M7te2idRa9rXK6LM81/3lZEXVOq6jqszxaMRoVbaya+/xYlOGHZOIReo0Gw7el39GOSt12Do/s3WxQH1CTlEAvy62hv54V6PWu5HaM2hFDKmWeHYQ+WvchEL3/yRbw+UZT7GfWyJUDy+wBgFqQteuTHZSvmzFc8j4qaB6jHdPoOFfkRu5wazEdWhXBQqipbgasbyXxXGTD/mV27IgyYY664puv/44lqZh1g5KXl93e7ykKq7V9EwLAmt2A7Iwn0UWJT4zMwa8+mQOva0csrpCDEBfYgQkG4/l4686F3VHjyWdupUO8wA2zdPQRb6jnU6MwrqlI2sVsbaWzh8a5pJDqag8mc+GNHuxEdRvF63Ga7eoEuKNrrwXwAW8JzzaspbWB1ox89kjJ5Gq46soxg943x/Sctg3dDU1IBqRSovqGL3r2INat5DtnoGKjvgv1/QJzYHYk7uuUzyHRpnIRfpxb/EzNl+05+kZAzTAjFE1ZW8Yc6xLdGaLFVy6HprFM4d/xVpJ+M5l/Mav7tJRm4IhduoFWKeGE7+WuhFnFk+q/XNCAtwPZX9FHV8S4QkM1T+KVNTrOsk1lcZbwMf/VC4ean8R8W3fqx9ZGPLUxwAMPs7OR5Ygo8AD4VmVO+Z1TKpExsS57S/8pbtHrIXeNQUsQpE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
