travis:
  secure:
    BINSTAR_TOKEN: psc0gAPrk5PF9RtdOPsLiz9wzPzdSZG2S200FNvns7XNqEp/CKzzCAdcWlG74mkSf+x8Vb2Ini9lMJBpUcC8wOm+eOisEAQ5jyabI1KcxhnAlX1Qfba3X7cY6n17aajx0+PWJHZZEwrz7KzpuAgKNQIokTLQ+2/lYZdk0i5o42aam7j7BECPkr3RYBVBNKV2Ukzb7ym0IGpMDbrGsGBcOX6pmRrFGwmtQmiS4RQyggbk9HgEA4wZS6GaKoSpjKaDMct6KzyRho7TyFTq+sIr8ZxY465z9yRAD3xGZBRAKON5ViAyMpUFNq198JpZHapgCiWErHv2qlztzgodyY/wr2OiLGhm/QG3kPRdFfhxrXocHe/0SB/BmyEQJJEt101I97kq4GYXNvobkEOKvrbs35225/OWhF/L1kV/+JZ4TkYd5BvDM0O5llGZrR2WYVXcBiXfqLDeA+nq3yMSaU5rk/UHl8Ye/dtBeqILqfq+Y7T6dFjtPsRDmcso02BbWv3f1fyoDfC4keEIG/22nQhiihVC0i659wpg9OY8nQ/8tbJfSG+WZgNQllcOUqx1QIuLZSFJB6ikceSdcSOFr27bQd6ebTJ+qjlzkLcQu7Svm9ZgbGO364NIqDiYKcPfqcH25vmUdTBtNBnW4DMroazjr/AxSDflyiTba7z9QzePAro=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
