travis:
  secure:
    BINSTAR_TOKEN: xS4dz9ZJb/N+yeNK7wXKueO/LTh6PZAp3uQ7dkt7xzo/V/ujsT72rGcKnvIFFcIVmWCIhjSaDiYmC2dhbU/U9xKTEkQ9xOTDKo6+s1PRFn/QBbQh+rFjovZIADXI71S+TSBakpM6IjaBHo8OdrOIQQ76hKVgEia/FTDv5NDaCOETDFfYrP6DTH6reIS988te1GpTHjNXXw1r8TMNBbFZ6FE91WfR279P69xXsY1x1KLuZM3/Dwvg98tyX45hStYMLKE0uHJHR+2BjP6IpbdE6d9Hiv8xYXjFmpZC0EMuYIzGWSSPMUO2oUspJNX46Sd0DZByvE2hRm8wGEN6PXa2+HY+/1o+3431Fj1Dajydzf3fLvBO9JMbXnuibQbX6zSkJw1tW2e1+n7Rq1k7Cf5xPdltzH3fVZH32cuvM4cRvf5d5e7vBO+cw8+Q9bSE9Z0/qsPI2FNvKiJETx0qvKgloaTqNtCmXIRyQ7TxQXCwr4ZzFjMY47/061XlR1/x+Jo/cAz+n3wRU6CjsSLTWjQTjPZ9veyfkgRmmG7BBzKwrEi5yGXwI6M7Rv5FLoupwRI7dpluwoWFUMJKEkvTBC5w9CzJVTqeeLxvyz1PWMH34ONxoN2ClOQ7/NVnJFLhKZG5axWJ/Vn4BBJBRKcHch41vO61EpRaR+zrcBDwC0cHWxs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
