travis:
  secure:
    BINSTAR_TOKEN: A1Yp7SB82HxCcWB7y4XVxgnispO52hdxPBAWiaY3CPiedh+yt7yEBIC9yuYw1zl32PJgiq19kfCOQGlIIUkXBlExGjfjLxlX2J+qUnyhW2CORj+SuwfQiGYCiSxYhTmmIwXAzUI/igvwKz0cgXJ8TCRadYJyZYi4TcU6JMF59zYbkoB+TpmLfQhcS4/pv4Lsijhd2dNM6px5wsmNdyQhMpOPcnaz28zsbQXAwHFlU79avy+WNkvFA1pZpVKeupwBqi/nrqHjgTbftcPYbpIyg2o2vCukqjyrBDVBPK884A0Yfj+67tiCS+IocAcb3qobn8bIQhY42kd4iRKQGnhn9r7KHAS5DtaV8QYTMcFoVn1kgzjkYrYFg4RX1mhLq9CiMrSWsO5BSl/mS/L6x40QLaDVMPqEzNNc5p6Cj9MxInbXO7KRV9UKUewuLBCRHPKzLycY+9aOkUpsALqPBibt32ZbJCsdfyVKQ6hXDo9gf9+Q1XAgf2mbZJ+39V+XqZHAFkP7rEs0rNcugE0d/5y0/NI0RGgQXTjqdJLDbrPx1EUk//jcyVgbZYkkn6+Z4SCtFzSMgXrznoTPKGULAB/UGBmAny65w5CrmikwlsokakN5f/Rqm15eJt3cX8BiTbk3NbJoulZz23N5AdOyPTtVo0dR5Pfci+Sd71TCs6WiqSQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
